### PR TITLE
Fixed output files

### PR DESCRIPTION
**Pull request by arthbous**
I fixed the output the creation of the output files to no delete the folder. That way we do not get kicked out of the folder everytime we redo the computation. And no need "shutil", os can do it.

I also added *.pyc to gitimore.

@maximilianmetti this is ready to merge

### CODE REVIEW

**Comment by maximilianmetti** [comment]
@arthbous did you pull? This was already fixed in the other PR. A fix is already in master

**Comment by arthbous** [comment]
I did. But this time it does not delete the folder so you do not get kicked out. It just delete the files

**Comment by maximilianmetti** [comment]
not sure what you mean by "kicked out".  this was working perfectly on my system. I thought clean was supposed to delete everything and remake it.

**Comment by arthbous** [comment]
I don't like it when it does that because I have to leave the folder and come back to it. This method now does not delete the folder but only delete files inside it.

For example, if you keep one terminal open on output/data_pnp/ you can stay there every time you run the code. If you delete le folder then you have to do a cd output/data_pnp every time

**Pull request merged**
